coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%

# This does not work: https://github.com/codecov/support/issues/260
comment: false
